insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (1, 'Auricular Void Elite', 'Nullam varius. Nulla facilisi.', 1109.78, 'mouse2.png', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0, 553, 2, '2021-04-08 03:15:35', '2021-12-21 14:52:45');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (2, 'Auricular Void Elite', 'Aliquam sit amet diam in magna bibendum imperdiet.', 3674.04, 'teclado2.png', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1, 662, 4, '2021-01-31 20:30:36', '2021-10-09 06:32:54');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (3, 'Teclado K65 RGB MINI 60%', 'Nullam molestie nibh in lectus.', 2354.7, 'pad1.jpg', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 0, 912, 3, '2021-02-05 13:28:39', '2021-07-28 18:13:55');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (4, 'Mouse M65', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2058.13, 'silla1.png', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 0, 548, 5, '2021-02-28 15:10:43', '2021-10-21 17:16:43');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (5, 'Mouse M65', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 2315.6, 'keyboard2.png', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, 821, 2, '2021-01-31 20:06:38', '2022-01-09 12:41:13');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (6, 'Auricular Void Elite', 'Nunc nisl.', 5551.99, 'mouse2.png', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, 616, 3, '2021-06-02 08:25:35', '2021-07-21 07:08:31');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (7, 'Accesorio remera m/l', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1640.49, 'teclado2.png', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 0, 390, 3, '2021-01-30 08:08:49', '2021-09-21 14:36:37');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (8, 'Teclado K65 RGB MINI 60%', 'Sed ante.', 4970.34, 'mouse1.jpg', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, 582, 4, '2021-06-29 10:57:15', '2021-10-29 00:16:31');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (9, 'Mouse Pad', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 3869.82, 'keyboard2.png', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 0, 63, 6, '2021-01-11 14:12:23', '2021-07-05 14:40:44');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (10, 'Auricular Void Elite', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 4468.47, 'mouse1.jpg', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, 923, 5, '2021-03-04 16:37:49', '2021-07-09 02:00:22');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (11, 'Accesorio remera m/l', 'Suspendisse accumsan tortor quis turpis.', 1888.9, 'remera.jpg', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, 411, 6, '2021-01-21 07:53:08', '2021-10-04 10:41:31');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (12, 'Accesorio remera m/l', 'Fusce consequat. Nulla nisl.', 5310.86, 'teclado2.png', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, 143, 2, '2021-04-05 05:20:26', '2021-10-13 18:27:29');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (13, 'Auricular Void Elite', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 5340.97, 'pad1.jpg', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 0, 844, 1, '2021-03-14 01:42:13', '2021-09-29 19:47:04');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (14, 'Auricular Void Elite', 'Quisque porta volutpat erat.', 2015.51, 'keyboard2.png', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 0, 918, 2, '2021-01-08 04:29:43', '2021-11-04 21:23:27');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (15, 'Mouse M65', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1001.6, 'auricular1.jpg', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, 262, 2, '2021-02-15 19:58:49', '2021-11-20 02:50:14');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (16, 'Mouse M65', 'Pellentesque ultrices mattis odio. Donec vitae nisi.', 2744.82, 'mouse1.jpg', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 0, 971, 5, '2021-03-22 06:11:24', '2021-09-24 23:50:36');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (17, 'Silla TC60 FABRIC', 'Nullam varius.', 1039.74, 'keyboard2.png', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 0, 48, 5, '2021-02-20 02:04:42', '2021-11-08 19:53:08');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (18, 'Accesorio remera m/l', 'Morbi non lectus.', 1005.96, 'mousepad2.png', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 0, 177, 4, '2021-01-29 21:56:26', '2021-09-10 21:41:59');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (19, 'Mouse M65', 'Praesent blandit lacinia erat.', 773.96, 'teclado2.png', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, 101, 1, '2021-02-13 12:25:17', '2021-08-03 15:33:34');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (20, 'Teclado K65 RGB MINI 60%', 'Integer ac neque. Duis bibendum.', 3251.15, 'mousepad2.png', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, 856, 2, '2021-03-21 22:43:34', '2021-08-14 09:20:52');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (21, 'Auricular Void Elite', 'Etiam faucibus cursus urna.', 2286.84, 'teclado2.png', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, 451, 5, '2021-02-07 16:06:37', '2021-08-12 02:02:35');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (22, 'Auricular Void Elite', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 2424.48, 'mousepad2.png', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.', 0, 426, 3, '2021-03-13 05:12:50', '2021-08-10 14:56:08');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (23, 'Auricular Void Elite', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1872.73, 'mouse1.jpg', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 1, 881, 1, '2021-01-07 00:46:46', '2021-11-28 10:19:06');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (24, 'Silla TC60 FABRIC', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 1800.05, 'mouse1.jpg', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 0, 48, 6, '2021-02-02 12:52:48', '2021-09-26 18:19:20');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (25, 'Teclado K65 RGB MINI 60%', 'Phasellus sit amet erat.', 1229.75, 'mouse2.png', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 0, 865, 6, '2021-01-02 13:52:28', '2022-01-06 07:12:41');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (26, 'Auricular Void Elite', 'Suspendisse accumsan tortor quis turpis.', 5988.98, 'pad1.jpg', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 0, 147, 4, '2021-03-21 03:49:23', '2021-07-03 21:17:42');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (27, 'Teclado K65 RGB MINI 60%', 'Pellentesque viverra pede ac diam.', 1692.01, 'pad1.jpg', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, 773, 3, '2021-01-05 23:57:52', '2021-09-28 19:18:19');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (28, 'Silla TC60 FABRIC', 'Proin risus. Praesent lectus.', 3538.44, 'teclado2.png', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 0, 489, 5, '2021-05-21 04:47:32', '2021-09-30 17:02:57');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (29, 'Mouse Pad', 'Curabitur convallis.', 3783.77, 'pad1.jpg', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 0, 932, 3, '2021-02-08 20:04:05', '2021-12-28 18:44:22');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (30, 'Accesorio remera m/l', 'Sed sagittis.', 1215.74, 'mouse2.png', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 0, 530, 4, '2021-03-24 06:22:32', '2021-11-30 17:38:03');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (31, 'Auricular Void Elite', 'In hac habitasse platea dictumst.', 1609.3, 'mousepad2.png', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, 205, 5, '2021-01-17 13:33:49', '2021-09-01 14:13:07');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (32, 'Silla TC60 FABRIC', 'Proin eu mi.', 3742.19, 'mouse1.jpg', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 0, 340, 4, '2021-03-29 23:47:50', '2021-12-05 15:42:31');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (33, 'Accesorio remera m/l', 'Nulla mollis molestie lorem. Quisque ut erat.', 1093.48, 'keyboard2.png', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 0, 181, 5, '2021-05-09 22:16:07', '2021-12-02 20:05:29');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (34, 'Accesorio remera m/l', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 2888.1, 'mousepad2.png', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 541, 3, '2021-01-14 22:32:29', '2021-08-20 04:18:26');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (35, 'Accesorio remera m/l', 'Nulla tellus.', 1849.45, 'mouse1.jpg', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 0, 681, 2, '2021-04-25 00:50:41', '2021-09-13 07:36:42');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (36, 'Silla TC60 FABRIC', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 1429.53, 'silla1.png', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 0, 683, 5, '2021-06-28 07:22:36', '2021-10-08 15:28:19');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (37, 'Silla TC60 FABRIC', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 4950.67, 'pad1.jpg', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, 363, 1, '2021-05-18 18:15:29', '2021-09-09 08:21:12');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (38, 'Accesorio remera m/l', 'Etiam justo. Etiam pretium iaculis justo.', 4130.92, 'remera.jpg', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, 717, 4, '2021-03-05 13:37:25', '2021-12-03 02:37:04');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (39, 'Mouse Pad', 'Aliquam non mauris. Morbi non lectus.', 3970.8, 'pad1.jpg', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0, 808, 6, '2021-01-08 00:49:55', '2021-08-09 15:08:03');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (40, 'Accesorio remera m/l', 'In hac habitasse platea dictumst.', 5811.2, 'auricular1.jpg', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, 485, 3, '2021-04-09 21:35:27', '2021-10-17 23:27:52');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (41, 'Auricular Void Elite', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 3515.98, 'pad1.jpg', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 1, 149, 3, '2021-06-03 13:40:58', '2021-10-21 06:39:38');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (42, 'Auricular Void Elite', 'Suspendisse accumsan tortor quis turpis. Sed ante.', 2268.9, 'teclado2.png', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, 602, 4, '2021-06-09 04:50:04', '2021-09-24 13:16:23');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (43, 'Teclado K65 RGB MINI 60%', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 5955.15, 'silla1.png', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 0, 648, 4, '2021-03-01 10:39:44', '2021-10-11 05:15:35');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (44, 'Mouse Pad', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 3825.52, 'mouse1.jpg', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1, 719, 5, '2021-02-22 13:51:28', '2021-10-29 00:36:34');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (45, 'Accesorio remera m/l', 'Nunc purus. Phasellus in felis.', 1743.57, 'auricular1.jpg', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 212, 4, '2021-04-01 09:18:16', '2021-11-03 13:07:36');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (46, 'Silla TC60 FABRIC', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 732.31, 'remera.jpg', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, 618, 5, '2021-02-09 14:37:28', '2021-07-05 14:36:11');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (47, 'Silla TC60 FABRIC', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 3883.73, 'remera.jpg', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 0, 788, 6, '2021-05-11 09:15:55', '2021-10-16 21:01:04');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (48, 'Mouse M65', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 5149.59, 'mouse1.jpg', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 0, 34, 3, '2021-03-30 04:29:15', '2021-09-04 21:33:11');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (49, 'Mouse M65', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 2611.78, 'teclado2.png', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 0, 697, 1, '2021-05-17 07:08:42', '2021-09-04 19:18:02');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (50, 'Silla TC60 FABRIC', 'Phasellus sit amet erat.', 866.45, 'mouse2.png', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 0, 346, 3, '2021-01-13 02:53:51', '2021-10-11 03:57:16');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (51, 'Mouse M65', 'Nam nulla.', 3833.82, 'mouse1.jpg', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 0, 294, 3, '2021-02-21 00:31:23', '2021-09-03 14:15:01');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (52, 'Mouse M65', 'Pellentesque ultrices mattis odio.', 4047.64, 'silla1.png', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 0, 366, 4, '2021-03-01 18:34:25', '2021-11-26 23:56:58');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (53, 'Mouse Pad', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 5270.66, 'keyboard2.png', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, 674, 4, '2021-02-26 19:46:56', '2021-07-16 22:12:24');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (54, 'Mouse M65', 'Praesent id massa id nisl venenatis lacinia.', 3859.49, 'auricular1.jpg', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, 974, 4, '2021-05-07 18:14:07', '2021-12-27 08:19:18');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (55, 'Auricular Void Elite', 'Fusce consequat.', 2240.18, 'keyboard2.png', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, 508, 4, '2021-04-09 00:57:13', '2021-08-15 17:03:46');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (56, 'Accesorio remera m/l', 'Cras in purus eu magna vulputate luctus.', 2544.27, 'mouse1.jpg', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 0, 208, 2, '2021-06-25 08:26:23', '2021-10-27 10:40:13');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (57, 'Mouse Pad', 'Donec semper sapien a libero.', 1497.69, 'mouse1.jpg', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 0, 780, 3, '2021-05-24 18:09:22', '2021-07-07 13:50:11');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (58, 'Accesorio remera m/l', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 3594.48, 'mouse1.jpg', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1, 614, 2, '2021-01-17 04:15:05', '2021-10-21 20:01:18');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (59, 'Accesorio remera m/l', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 2692.01, 'auricular1.jpg', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, 93, 1, '2021-02-07 21:14:00', '2021-09-13 16:14:15');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (60, 'Teclado K65 RGB MINI 60%', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 4539.26, 'remera.jpg', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 0, 606, 4, '2021-06-02 07:46:20', '2021-09-12 23:22:03');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (61, 'Teclado K65 RGB MINI 60%', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 2530.09, 'silla1.png', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 0, 707, 5, '2021-01-01 19:31:11', '2021-10-10 08:51:50');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (62, 'Teclado K65 RGB MINI 60%', 'Pellentesque viverra pede ac diam.', 1716.07, 'teclado2.png', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, 411, 1, '2021-01-15 06:18:41', '2021-10-22 20:51:53');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (63, 'Auricular Void Elite', 'Nulla nisl. Nunc nisl.', 1632.13, 'silla1.png', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0, 728, 6, '2021-02-09 21:15:55', '2021-08-03 05:42:31');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (64, 'Accesorio remera m/l', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 4251.73, 'mouse1.jpg', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0, 599, 1, '2021-01-13 07:20:30', '2021-11-06 07:10:41');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (65, 'Mouse Pad', 'Morbi non lectus.', 5039.33, 'mouse1.jpg', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 515, 5, '2021-01-14 19:58:30', '2021-12-03 10:17:21');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (66, 'Teclado K65 RGB MINI 60%', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 3175.89, 'auricular1.jpg', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 0, 654, 4, '2021-04-04 12:30:07', '2021-08-13 20:23:27');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (67, 'Accesorio remera m/l', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 5492.73, 'mouse1.jpg', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, 699, 1, '2021-02-21 15:27:01', '2021-10-31 22:55:00');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (68, 'Teclado K65 RGB MINI 60%', 'Suspendisse accumsan tortor quis turpis.', 550.78, 'mouse1.jpg', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, 808, 1, '2021-03-06 22:46:48', '2021-08-12 20:31:02');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (69, 'Auricular Void Elite', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 3788.78, 'teclado2.png', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 0, 432, 5, '2021-03-19 11:47:01', '2021-12-03 15:44:21');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (70, 'Mouse Pad', 'In congue.', 1140.1, 'remera.jpg', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, 359, 2, '2021-04-25 05:04:34', '2021-09-18 05:11:08');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (71, 'Mouse M65', 'Nulla facilisi.', 3258.06, 'keyboard2.png', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, 746, 3, '2021-04-12 13:28:37', '2021-09-03 22:15:33');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (72, 'Teclado K65 RGB MINI 60%', 'Etiam faucibus cursus urna. Ut tellus.', 3135.31, 'auricular1.jpg', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, 267, 3, '2021-05-04 22:23:00', '2021-11-07 17:22:23');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (73, 'Silla TC60 FABRIC', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 4176.12, 'mousepad2.png', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 0, 15, 2, '2021-05-20 02:50:59', '2021-10-11 11:51:19');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (74, 'Teclado K65 RGB MINI 60%', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1977.12, 'silla1.png', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, 933, 2, '2021-06-15 12:02:49', '2022-01-08 13:34:15');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (75, 'Mouse M65', 'Proin risus.', 4470.5, 'teclado2.png', 'Fusce consequat. Nulla nisl. Nunc nisl.', 0, 711, 4, '2021-04-13 22:37:16', '2021-08-02 15:49:39');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (76, 'Mouse M65', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 5864.55, 'mouse1.jpg', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.', 0, 263, 3, '2021-02-10 02:14:47', '2021-09-07 04:17:14');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (77, 'Mouse Pad', 'Curabitur in libero ut massa volutpat convallis.', 2834.18, 'pad1.jpg', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 0, 528, 3, '2021-01-28 00:05:08', '2021-09-16 15:06:13');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (78, 'Auricular Void Elite', 'In sagittis dui vel nisl.', 5381.87, 'remera.jpg', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1, 358, 3, '2021-06-08 22:55:26', '2021-11-07 22:27:03');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (79, 'Silla TC60 FABRIC', 'Phasellus in felis.', 2797.34, 'silla1.png', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1, 769, 3, '2021-01-08 15:01:40', '2022-01-06 07:32:56');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (80, 'Accesorio remera m/l', 'Nam tristique tortor eu pede.', 2136.21, 'mousepad2.png', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 0, 566, 3, '2021-01-31 14:45:18', '2021-07-07 10:02:42');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (81, 'Mouse M65', 'Cras non velit nec nisi vulputate nonummy.', 5249.83, 'mouse1.jpg', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 0, 520, 5, '2021-01-19 07:46:32', '2021-10-26 06:25:31');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (82, 'Mouse Pad', 'Duis mattis egestas metus.', 2466.45, 'remera.jpg', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 0, 436, 5, '2021-04-06 14:10:20', '2021-09-04 04:36:14');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (83, 'Teclado K65 RGB MINI 60%', 'In eleifend quam a odio.', 4811.2, 'auricular1.jpg', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 0, 226, 1, '2021-03-09 21:43:30', '2021-11-10 17:08:51');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (84, 'Teclado K65 RGB MINI 60%', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1874.43, 'mouse1.jpg', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 0, 514, 5, '2021-04-08 12:15:58', '2021-08-26 02:59:15');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (85, 'Accesorio remera m/l', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 899.32, 'auricular1.jpg', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 0, 33, 1, '2021-05-30 01:50:33', '2021-11-15 23:29:14');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (86, 'Silla TC60 FABRIC', 'Fusce posuere felis sed lacus.', 4663.57, 'pad1.jpg', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1, 375, 4, '2021-03-24 15:06:58', '2021-10-03 14:01:14');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (87, 'Accesorio remera m/l', 'Nunc purus. Phasellus in felis.', 4480.7, 'remera.jpg', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, 660, 1, '2021-06-08 08:32:54', '2021-07-27 03:02:27');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (88, 'Accesorio remera m/l', 'Maecenas pulvinar lobortis est.', 901.93, 'keyboard2.png', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1, 750, 2, '2021-02-04 09:27:23', '2022-01-01 09:12:12');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (89, 'Mouse M65', 'Aliquam sit amet diam in magna bibendum imperdiet.', 1844.11, 'mouse1.jpg', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 0, 910, 5, '2021-01-24 02:27:43', '2021-07-06 06:25:09');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (90, 'Auricular Void Elite', 'Integer ac neque.', 1568.87, 'mousepad2.png', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 0, 226, 2, '2021-06-09 11:17:50', '2021-11-30 23:28:00');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (91, 'Accesorio remera m/l', 'Aliquam erat volutpat.', 4548.61, 'remera.jpg', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1, 974, 6, '2021-02-18 09:54:41', '2021-10-12 22:58:02');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (92, 'Accesorio remera m/l', 'Suspendisse potenti. In eleifend quam a odio.', 4548.35, 'mouse1.jpg', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1, 56, 1, '2021-02-04 14:54:44', '2021-08-08 21:49:01');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (93, 'Silla TC60 FABRIC', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 5625.49, 'teclado2.png', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 0, 54, 4, '2021-04-06 10:09:22', '2021-07-01 17:29:47');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (94, 'Mouse Pad', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 5662.52, 'mouse2.png', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, 310, 2, '2021-01-22 03:55:53', '2021-12-21 00:47:47');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (95, 'Mouse Pad', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 4290.61, 'mouse1.jpg', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, 841, 1, '2021-02-02 09:49:42', '2021-09-30 18:00:57');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (96, 'Teclado K65 RGB MINI 60%', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 3029.41, 'mousepad2.png', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 0, 9, 6, '2021-04-11 19:35:10', '2021-07-07 05:58:26');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (97, 'Auricular Void Elite', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 2826.76, 'teclado2.png', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 0, 396, 2, '2021-03-06 11:30:12', '2021-08-14 12:03:47');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (98, 'Mouse Pad', 'Nulla tempus.', 3546.03, 'mouse1.jpg', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 0, 884, 4, '2021-05-10 01:00:39', '2021-09-04 20:13:19');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (99, 'Teclado K65 RGB MINI 60%', 'Proin eu mi.', 4742.14, 'mousepad2.png', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 0, 562, 4, '2021-05-26 07:59:07', '2021-11-16 14:11:17');
insert into productos (id, titulo, descripcion, precio, img, caracteristicas, isRecommended, stock, categoria_id, created_at, updated_at) values (100, 'Teclado K65 RGB MINI 60%', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 4330.01, 'teclado2.png', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 0, 622, 4, '2021-05-05 20:29:59', '2021-12-08 12:19:48');
